const express = require("express");
const message = require("../components/message/network");
const user = require("../components/user/network");
const chat = require("../components/chat/network");
const tipoBarrio = require("../services/1.network/tipoBarrioNetwork");
const area = require("../services/1.network/areaNetwork");
const barrios = require("../services/1.network/barriosNetwork");
const ruta = require("../services/1.network/rutaNetwork");
const tipoVivienda = require("../services/1.network/tipoViviendaNetwork");
const actividadEconomica = require("../services/1.network/actividadEconomicaNetwork");
const entidad = require("../services/1.network/entidadNetwork");
const familia = require("../services/1.network/familiaNetwork");
const historialMedico = require("../services/1.network/historialMedicoNetwork");
const persona = require("../services/1.network/personaNetwork");
const personaAdulta = require("../services/1.network/personaAdultaNetwork");
const personaJoven = require("../services/1.network/personaJovenNetwork");
const personaMenor = require("../services/1.network/personaMenorNetwork");
const tipoEducacion = require("../services/1.network/tipoEducacionNetwork");
const tipoEntidad = require("../services/1.network/tipoEntidadNetwork");
const tipoPersona = require("../services/1.network/tipoPersonaNetwork");
const data = require("../services/1.network/dataNetwork");

const routes = server => {
  server.use("/message", message);
  server.use("/user", user);
  server.use("/chat", chat);
  server.use("/tipoBarrio", tipoBarrio);
  server.use("/area", area);
  server.use("/barrios", barrios);
  server.use("/ruta", ruta);
  server.use("/tipoVivienda", tipoVivienda);
  server.use("/actividadEconomica", actividadEconomica);
  server.use("/entidad", entidad);
  server.use("/familia", familia);
  server.use("/historialMedico", historialMedico);
  server.use("/persona", persona);
  server.use("/personaAdulta", personaAdulta);
  server.use("/personaJoven", personaJoven);
  server.use("/personaMenor", personaMenor);
  server.use("/tipoEducacion", tipoEducacion);
  server.use("/tipoEntidad", tipoEntidad);
  server.use("/tipoPersona", tipoPersona);
  server.use("/data", data);
};

module.exports = routes;
